language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
before_install:
  - pip install coveralls
install:
  - pip install -e .

script: nosetests -w tests/unit --with-coverage --cover-package=quickbooks
after_success:
  - coveralls
